<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>RateChats Receipt Document</title>
    <style >
        h1{
            text-align: center;
            font-size: 18px;
        }
        .jumbotron {
            background-color: #f4511e;
            color: #fff;
            padding: 60px 25px 10px 25px;
            font-family: Montserrat, sans-serif;
            text-align: center;
        }
        .stale{
            color: #000;
            font-weight: 500;
        }

        .img-thumbnail {
            display: inline-block;
            max-width: 100%;
            height: auto;
            padding: 4px;
            line-height: 1.42857143;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 4px;
            -webkit-transition: all .2s ease-in-out;
            -o-transition: all .2s ease-in-out;
            transition: all .2s ease-in-out;
        }
        .container-fluid {
            padding-right: 15px;
            padding-left: 15px;
            margin-right: auto;
            margin-left: auto;
        }
        .col-sm-6 {
            width: 50%;
        }
        .row {
            margin-right: -15px;
            margin-left: -15px;
        }
        .bg-grey {
            background-color: #f6f6f6;
        }
        #item{
            float: left;
        }
        #person{
            float: right;
        }
        .contents{
            padding: 10px 5px 10px 20px;
        }
        .jumbosmall {
            margin-top: 5px;
            background-color: #f4511e;
            color: #fff;
            padding: 10px 25px;
            font-family: Montserrat, sans-serif;
            text-align: center;
        }
        .jumbosmall ul, .jumbosmall ul li a {
            color: #fff;
            list-style: none;
        }

        .clear{
            clear: both;
        }
    </style>
</head>

<body>
<div class="jumbotron">
    <img src="<?php echo URL; ?>public/images/unizik_logo.jpg" class="img-thumbnail center-block" alt="Image" width="80" height="80">
    <h1> <?php $header = isset($this->header)? $this->header: "RateChats Receipt"; echo $header; ?></h1>
</div>
<div class="container-fluid">
    <h1>Hostel/ Room Reservation Invoice</h1>
    <hr/>
    <div class="row">
        <div class="col-sm-6" id="item">
            <div class="contents">

                <h4>FOR: </h4>
                <h2>UNIVERSITY LODGE, Ifite - Awka</h2>
                <h4>ADDRESS:<br> Welcome to Living Faith Hostel, Ifite - Awka, where God turns little shots to big shots in a short time... and the intro continues</h4>
                <h4>How to make payments: </h4>
                <h4>BANK DETAILS:<br> Welcome to Living Faith Hostel, Ifite - Awka, where God turns little shots to big shots in a short time... and the intro continues</h4>


            </div>
        </div>
        <div class="col-sm-6 bg-grey" id="person">
            <div class="contents">
                <h4>REQUEST BY: </h4>
                <h2>Chinonso Ani Onwubiko</h2>
                <h4>ADDRESS:<br> Welcome to Living Faith Hostel, Ifite - Awka, where God turns little shots to big shots in a short time... and the intro continues</h4>
                <p><strong>Phone:</strong> 07035553322 </p>
                <p><strong>Email:</strong> a full documentation of Hostel programs and activities, please download the documentation below.  </p>
                <h4>TRANSACTION: </h4>
                <hr/>
                <h2>Room 103b</h2>
                <h4><strong>Amount:</strong>130,000 </h4>
                <p><strong>Status: </strong> Payment Not Yet Made</p>

            </div>




        </div>
    </div>
</div>
<br class="clear"/>
<footer class="jumbosmall">
    <h4>Once payment has been made: Follow www.RateChats.com.ng/payment/made/78232 to validate this invoice</h4>
    <hr/>
    <h3> Quick Links</h3>
    <div class="row text-left">
        <div class="col-sm-4">
            <ul class="list-unstyled">
                <li> Register as a </li>
                <li> Register as a Hostel Manager</li>
                <li> Register Hostel </li>
            </ul>
        </div>
    </div>
    <hr/>
    <p class="stale">This invoice will be marked as stale if transaction is not completed in 24 hours</p>
    <p class="center-block">Digitally Generated by RateChats All rights reserved &copy; 2016 - <?php echo(date('Y')); ?></p>


</footer>

</body>
</html>